runtime: nodejs18

env_variables:
  DB_USER: admin
  DB_PASS: 1234
  DB_NAME: auth_db
  DB_PORT: 3306
  INSTANCE_HOST: 10.107.128.3
  DB_ROOT_CERT: certs/server-ca.pem
  DB_CERT: certs/client-cert.pem
  DB_KEY: certs/client-key.pem
  PRIVATE_IP: TRUE

vpc_access_connector:
  name: projects/maurea-project-test/locations/asia-southeast2/connectors/appengine-sql-connector 
